name: amazon_clone
description: A Amazon clone project, made with Flutter and NodeJs.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  cloudinary_public: ^0.11.0
  dotted_border: ^2.0.0+2
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  very_good_analysis: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - asset/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
